project_name: image-decorator-controller

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    binary: image-decorator-controller
    goos:
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - maintainer: Emre Odabas<emreodabas@gmail.com>
    description: Image Decorator Controller Manager
    homepage: https://github.com/emreodabas/image-decorator-controller
    license: Apache2
    formats:
      - deb
      - rpm