name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: image-decorator-controller
      run: go test -v ./...
    - name: GoReleaser Action
      uses: goreleaser/goreleaser-action@v2.4.1
